verbose function added; minor help update

diff --git a/pdsu b/pdsu
--- a/pdsu
+++ b/pdsu
@@ -1,4 +1,3 @@
-#!/bin/bash
 
 # Initiate the Dell firmware updates from the admin node
 # limits a number of processes to NP and number of the nodes
@@ -18,9 +17,17 @@
 # catching signals to make sure the clean exit
 trap 'killall $(jobs -p) 2>/dev/null; exit 1' 1 2 3 6
 
+
+# for a sake of debuging, works with the '-v'
+verbose() {
+  if [[ $VERBOSE == 'yes' ]]; then
+    (($#)) && echo "VERBOSE: $@"
+  fi
+}
+
 # help function
 usage() {
-  (($#)) && echo -e "\nError: $@"
+  (($#)) && echo -e "\nERROR: $@"
   echo
   echo "Usage: ${0##*/} [options] nodelist"
   echo '        nodelist is a comma-separated list with a prefixNN naming convention'
@@ -35,7 +42,7 @@ usage() {
   exit 1
 }
 
-VERBOSE=':'
+VERBOSE='' # by default, no verbose mode
 DSUREBOOT='' # by default, no reboot initiated by DSU
 
 # getopt formats input into a '$0 options -- args'
@@ -47,7 +54,7 @@ while true; do
   case ${1} in
     -h) usage ;;
     -r) DSUREBOOT='--reboot' ;;
-    -v) unset VERBOSE ;;
+    -v) VERBOSE='yes' ;;
     -s) shift; RN=$1 ;;
     -t) shift; TIMEOUT=$1 ;;
     -n) shift; NP=$1 ;;
@@ -75,11 +82,11 @@ RUNDSU='rundsu' # temporary script for the remote execution
 [[ -d $DSUTEMP ]] || mkdir -p $DSUTEMP
 cd $DSUTEMP
 
-$VERBOSE echo NODES: $NODES
-$VERBOSE echo NP: $NP
-$VERBOSE echo RN: $RN
-$VERBOSE echo TIMEOUT: $TIMEOUT
-$VERBOSE echo bootstrap file: $DSUTEMP/$BOOTSTRAP_FILE
+verbose NODES: $NODES
+verbose NP: $NP
+verbose RN: $RN
+verbose TIMEOUT: $TIMEOUT
+verbose bootstrap file: $DSUTEMP/$BOOTSTRAP_FILE
 
 # get the dell's bootstrap file
 echo "...Downloading $BOOTSTRAP_FILE file" 
@@ -92,11 +99,11 @@ sed -i 's/IMPORT_GPG_CONFIRMATION="na"/IMPORT_GPG_CONFIRMATION="yes"/' $BOOTSTRA
 
 # a string like node[2-4,7],gpu6 to a list 'node2 node3 node4 node7 gpu6 ...'
 NODELIST=$(shosts $NODES)
-$VERBOSE echo NODELIST: $NODELIST
+verbose NODELIST: $NODELIST
 pdcp_cmd="pdcp -f $NP -b -w $NODES"
-$VERBOSE echo pdcp command: $pdcp_cmd ...
+verbose pdcp command: $pdcp_cmd ...
 dsu_cmd="dsu -n --import-public-key $DSUREBOOT"
-$VERBOSE echo DSU command: $dsu_cmd
+verbose DSU command: $dsu_cmd
 
 
 ## the action starts here
@@ -126,7 +133,7 @@ rundsu() {
 
   ssh -o ConnectTimeout=12 $NODE "bash $RD/$RUNDSU"  # actual run
   SSHST=$?  # status of the SSH command (== the latest executed command)
-  $VERBOSE echo SSH exit code for $NODE: $SSHST
+  verbose $NODE: SSH DSU exit code: $SSHST
 
   # exit codes for the DSU
   HELPURL='https://www.dell.com/support/manuals/en-us/system-update/dsu_ug_1.8_revamp/dsu-return-codes?guid=guid-a413b447-0dd2-45fb-a60c-7a472e353e30'
@@ -135,24 +142,28 @@ rundsu() {
     8|26)
       # 8 Reboot is required for the update to be completed successfully
       # 26 Out-of-date updates are selected. For successful updates, reboot is required
-      echo $NODE: SSH DSU exit code: $SSHST
       echo $NODE: DSU run is over, draining for the reboot
       scontrol update nodename=$NODE state=drain reason=reboot
     ;;
     0|34)
       # 34 There are no updates found which can be applied
-      echo $NODE: SSH DSU exit code: $SSHST
-      echo $NODE: DSU run is over, resume the node if needed
+      echo $NODE: DSU run is over
+      if [[ $DSUREBOOT == '--reboot' ]]; then
+        echo $NODE: DSU reboot has been initiated, check the node manually later
+      else echo $NODE: Check the node manually, resume it if needed
+      fi
       #scontrol update nodename=$NODE state=resume
     ;;
     1|24)
       # 1 means something went wrong, like failure with the catalog
       # 24 Failure in applying updates
       echo $NODE: DSU run has failed with the exit code: $SSHST
+      echo $NODE: Check the node manually, we do nothing here
       return 1
     ;;
     *)
-      echo $NODE: DSU run has failed with the unknown exit code: $SSHST 
+      echo $NODE: DSU run has ended with the non-zero exit code: $SSHST 
+      echo $NODE: Check the node manually, we do nothing here
       echo see $HELPURL
       return 1
   esac
@@ -176,15 +187,15 @@ for n in $NODELIST; do
 
   # check how many bg jobs we have currently running
   update_cnp
-  $VERBOSE echo running jobs: cnp: $cnp
+  verbose echo running jobs: cnp: $cnp, limit: $NP
 
   # check number of the $NODES in the reboot|rebooting stage
   update_crn
-  $VERBOSE echo nodes in reboot: crn: $crn
+  verbose nodes in reboot: crn: $crn, limit: $RN
 
   # if $cnp is greater or equal to $NP: sleep
   # if $crn is greater or equal to $RN: sleep
-  while (( $cnp >= $NP || $crn >= $RN )); do
+  while (( $cnp >= $NP || ($crn+$cnp >= $RN) )); do
     sleep $TIMEOUT # timeout between checking the jobs number
     update_cnp
     update_crn
